### ISSUE TITLE
Practica

### ISSUE THREAD

**Issue by josealfredo79** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-irving1613#1]
Aqui debe ir la practica con su calificación de acuerdo a la rúbrica

**Comment by irving1613** [comment]
[practica - Irving Zárate Reyes.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-irving1613/files/7221960/practica.-.Irving.Zarate.Reyes.pdf)

**Comment by RicardoMtzSts** [comment]
EXELENTE TRABAJO 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
